[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "presentation"
  name = "Pres"
  url = "presentation"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "gallery"
  name = "Cartoon"
  url = "gallery/cartoon"

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 4
